services:
  pgsql:
    image: postgres:16-alpine
    env_file: "../envs/service-pgsql.env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  pgsqldata:
    driver: local
    driver_opts:
      type: none
      device: ../openbas_persistent_volumes/pgsqldata
      o: bind


